### ISSUE TITLE
【pripara-lives.csv】6話挿入歌「太陽のflare sherbet」はライブではない

### ISSUE THREAD

**Issue by mikimiki4748** [prickathon/prismdb#106]
ライブを行った記録として保存してありますが、
この回ではみれいがプリパス内でそふぃ様のライブ中継を見ていただけのようです。
1:10~1:20の間にアウトロしか曲が流れておらず、ライブ記録としては不適切かもしれません。

**Comment by takanakahiko** [comment]
そうですね〜修正したい
