### ISSUE TITLE
事例集がほしい

### ISSUE THREAD

**Issue by takanakahiko** [prickathon/prismdb#124]
> `https://prismdb.takanakahiko.me/sparql/`
> 
> ここに行って
> ↓こうやるとそらみスマイルのライブ一覧が出るよ、みたいな事例集ほしい
> 
> ```
> PREFIX prism: <https://prismdb.takanakahiko.me/prism-schema.ttl#>
> 
> SELECT ?n ?st ?title
> WHERE {
>     ?live a prism:Live;
>         prism:performer "solami_smile";
>         prism:songPerformed/prism:name ?title;
>         prism:liveOfEpisode ?ep.
>     ?ep a prism:Episode;
>         prism:話数 ?n;
>         prism:サブタイトル ?st.  
> }
> ORDER BY ?n
> ```

とのご意見を @banjun さんよりいただきました

**Comment by banjun** [comment]
#109 にもあるよ

**Comment by takanakahiko** [comment]
ダブった...! 閉じます!
