### ISSUE TITLE
Fargateにする

### ISSUE THREAD

**Issue by takanakahiko** [prickathon/prismdb#143]
安いらしい

**Comment by takanakahiko** [comment]
とりあえず， `docker-compose.yml` やコンテナ間の参照をすこし弄って

```
$ docker-compose build
$ ecs-cli push prismdb_sparpl
$ ecs-cli push prismdb_nuxt
$ ecs-cli push prismdb_restapi
$ ecs-cli compose up
```

でリリースできることろまで来ました．
あとはこれをCIに反映すれば...

**Comment by takanakahiko** [comment]
`ecs-cli compose up` をする毎に公開されるIPアドレスが変わってしまうので，ALBを挟む必要性がある...？調査します．

**Comment by takanakahiko** [comment]
ALB を Fargate に向ける方法がわからず．
Target Group の VPC を Fargate の VPC に設定するだけじゃダメなのか...?

**Comment by takanakahiko** [comment]
`ecs-cli compose up` はあくまでもタスク定義まで行うコマンドで，サービスの開始は行われていなかった．結果としてELBが503を返したいたのだが，これを理解できずに結構つまづいた...．
手動でサービスを立ち上げたときにELBを設定したので動いたのだけど，これは自動化しなければ...

**Comment by nagait84** [comment]
@takanakahiko 
> ALB を Fargate に向ける方法がわからず．
> Target Group の VPC を Fargate の VPC に設定するだけじゃダメなのか...?

fargateだとターゲットグループの設定で「ターゲットの種類」を
「インスタンス」ではなく「IP」にするのがよく忘れがちな設定ですが、こちらは設定していましたでしょうか。
IPになっていたら、ALBうまくいくとおもいます
←マネジメントコンソールでぽちぽちして、うまくいけたらiacする勢なのでこんな説明ですが、参考になればと

**Comment by takanakahiko** [comment]
Fargate にして少し計測したところ，あまり安くなりませんでした．
EC2の前にあるALBをEIPに変更して節約することにしました．
