### ISSUE TITLE
Itemの弾がprismdbのデータだけで判断できない

### ISSUE THREAD

**Issue by sergeant118** [prickathon/prismdb#156]
追加する時はCSVに分けてるけどデータ取り出す時は特定の弾だけ取り出すのがやや複雑。
アプリで〇〇弾のコーデの一覧だけ欲しいみたいな用途で簡単に使えるような構造だと嬉しい
ジュエル3弾ならidがJ3から始まるとか、すずチャンネルとリングマリィチャンネルが3弾みたいな別の知識が必要になってしまう

**Comment by takanakahiko** [comment]
'弾' っていうデータ構造作ってもいいかもですね

|key|name|
|---|---|
|J3|ジュエル3弾|

みたいな?

**Comment by sergeant118** [comment]
ついでに各弾のサブタイトルもまとめたいなって気持ちはもあります。使うかどうかはさておき

Itemのカラムには埋め込まずに別途作る感じですかね？

**Comment by takanakahiko** [comment]
「どっちのほうが追加が手間か」になってきますね．
アイテム追加主要コントリビュータである，ぐんそーさん次第な気もしてます．

**Comment by sergeant118** [comment]
・別に作る
 とても簡単。
ただし弾内別チャンネルがよくわからん問題があまり解決出来ていないように思う

・Itemに追加する
手間はかかる。
アイテムのページを1つ見た時に直感的に分かるのが利点。
データが長くなるけどROD的には気にすることない(んでしたっけね？)
弾に含まれないPR系のItemにとっては無駄カラムになる(今更？)

と一長一短な感じはしますが、後者のデメリット(？)が問題なければ後者推しではあります

**Comment by takanakahiko** [comment]
メリットとデメリット，僕も同じ感じで考えていました．
ではとりあえず，後者にしましょうか．
何か不便があれば再度検討しましょう．
