### ISSUE TITLE
PrismDB is down

### ISSUE THREAD

**Issue by sue445** [prickathon/prismdb#186]
https://prismdb.takanakahiko.me/ is down 😢 

![image](https://user-images.githubusercontent.com/608755/66711296-1bf62580-edc4-11e9-81c2-6c63d715d604.png)

![image](https://user-images.githubusercontent.com/608755/66711304-39c38a80-edc4-11e9-9391-0d6dcaaf7a6b.png)

**Comment by takanakahiko** [comment]
ウオー確認します…。
（デプロイフローとインフラ周り見直した方が良さそう）

**Comment by takanakahiko** [comment]
Cloudflare 側の設定に問題がありました... 🙇 (直しました)

**Comment by sue445** [comment]
サイト落ちてるのに気づけるように外形監視あるとよさそう

**Comment by takanakahiko** [comment]
@sue445 外形監視について全然知見がないんですが，サクッと用意できる仕組みとかってご存知でしょうか？

**Comment by sue445** [comment]
無料で使えるのだと https://uptimerobot.com/ とかどうでしょう？

軽くググった感じだとSlack連携までやってくれるみたいです

* [外形監視サービス Uptime Robot が素晴らしい - blog.yukirii.dev](https://blog.yukirii.dev/uptime-robot/)
* [HTTP監視サービスUptime Robotについて | 稲葉サーバーデザイン](https://inaba-serverdesign.jp/blog/20170703/uptime_robot.html)

**Comment by takanakahiko** [comment]
ありがとうございます！導入してみました！
