### ISSUE TITLE
prism:name_kanaをひらがなにしたい

### ISSUE THREAD

**Issue by banjun** [prickathon/prismdb#214]
PrismDBを使って，かな→名前の変換辞書を作ろうとしていたのですが， `prism:name_kana`にひらがなカタカナが混在しているとして扱うかどうか悩んでいます。name_kanaはひらがな，という縛りがあると簡単そうですが，カタカナを登録したいユースケースもあるのか？ が気になります。現状ではかなカナ使いわけはなにかあるんでしょうか。

https://prismdb.takanakahiko.me/sparql?qtxt=PREFIX+prism%3A+%3Chttps%3A%2F%2Fprismdb.takanakahiko.me%2Fprism-schema.ttl%23%3E%0D%0A%0D%0ASELECT+replace%28%3Fckana%2C+%22+%22%2C+%22%22%29+as+%3Fckana%2C+replace%28%3Fcname%2C+%22+%22%2C+%22%22%29+as+%3Fcname%0D%0AWHERE+%7B%0D%0A++++%3Fc+a+prism%3ACharacter%3B%0D%0A++++++++prism%3Aname+%3Fcname%3B%0D%0A++++++++prism%3Aname_kana+%3Fckana.%0D%0A%7D

<img width="275" alt="image" src="https://user-images.githubusercontent.com/11156/71540054-b0663200-2988-11ea-9d5b-1267f05acea1.png">

<img width="277" alt="image" src="https://user-images.githubusercontent.com/11156/71540058-b9ef9a00-2988-11ea-9ab3-283349f915e8.png">

**Comment by takanakahiko** [comment]
データソースはこちらでした
https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AA%E3%83%91%E3%83%A9_(%E3%82%A2%E3%83%8B%E3%83%A1)

ここでカタカナにしている意図はわかりませんが、少なくとも今回のケースではひらがなに統一した方が良さそうですね。

**Comment by banjun** [comment]
なるほどですね
