### ISSUE TITLE
ライブ定義CSVのperformer に関する提案

### ISSUE THREAD

**Issue by takanakahiko** [prickathon/prismdb#228]
注 : 大文字で始まる英字はクラス，小文字で始まる英字は語彙です

メモ段階です

## 概要

語彙 performer を Live から 「Character および Team」あるい「Performer」へ向けたい

## メモ

https://github.com/prickathon/prismdb/pull/224

ここで，Liveの出演者における語彙について議論があった

- Liveの出演者に team という語彙で個人が指定されるのは不自然
- また，型の区別があいまいになる
- よって character という語彙を追加し，出演者が個人の場合はそちらへ向けることに
- 「アーティストとして取りうる値をクラスとして定義化したい」とめ，「個人が歌う場合は一人のチームを作る」という案があったが，現状直ぐに適用するのは困難であると判断

現時点の問題として以下がある

- CSVのカラム名と語彙が異なるので，複雑さが増しているように感じる( というかカラム設定CSV，例えば `_data/live/pripara-lives-columns.csv ` の `predicate` 列が不要な気がしていて，撤廃しようと何となく考えていた)
- 「character および team どちらか一方しか指定できない」みたいな制約ができないので，レビューが手間になる＆ミスが増える(現状は仕組みで防げない)

ここらへんの対応策として考えられて，どうするかなと考えている

1. performer 列の値に `team/` `characters/ `を付けるようにする
2. performer 列で Performer をしてして，Performer 側から Character および Team への参照を飛ばす

**Comment by banjun** [comment]
方向性の話ではなく，現状の事実の修正だけ:

> よって character という語彙を追加し，出演者が個人の場合はそちらへ向けることに

characterという語彙は追加**されておらず**，characterという**カラムが追加された** ，状態です。
したがって， 案1の 「performer 列の値に team/ characters/ を付けるようにする」と等価な状態です(現状の仕組みで，生成されるDBに影響を与えずに，どちらの手段も取れるはず)

**Comment by banjun** [comment]
Performerを置いたらどうなるのか実験として...

らぁらソロ:

`<performer/manaka_laala> prism:member <character/manaka_laala>`
`<performer/manaka_laala> prism:name "真中 らぁら"` (nameはあるのか？member/nameと一致)

らぁら&みれぃ:

`<performer/laala_and_mirei> prism:team <team/laala_and_mirei>`
`<performer/laala_and_mirei> prism:name "らぁら&みれぃ"` (team/nameと一致)

...または...

`<performer/laala_and_mirei> prism:member <character/manaka_laala>`
`<performer/laala_and_mirei> prism:member <character/minami_mirei>`
`<performer/laala_and_mirei> prism:name "らぁら&みれぃ"` (二人以上だとしてもnameは常にあるのか？)

SoLaMi♡SMILE:

`<performer/solami_smile> prism:team <team/solami_smile>`
`<performer/solami_smile> prism:name "SoLaMi♡SMILE"` (team/nameと一致)


...または...

`<performer/solami_smile> prism:member <character/manaka_laala>`
`<performer/solami_smile> prism:member <character/minami_mirei>`
`<performer/solami_smile> prism:member <character/hojo_sophie>`
`<performer/solami_smile> prism:name "SoLaMi♡SMILE"` (performer自体がteamの繰り返し定義にみえてしまう)

で，Liveのperformerカラムには `manaka_laala` `laala_and_mirei` `solami_smile` ... を書く的な。


SoLaMiDressing&Falulu:

`<performer/solami_dressing_and_falulu> prism:team <team/solami_dressing>`
`<performer/solami_dressing_and_falulu> prism:member <character/falulu>`
`<performer/solami_dressing_and_falulu> prism:name "SoLaMiDressing&Falulu"`  (この例はきれいに表現できているように見える・・・？)


なんとなく，PerformerからTeam or Characterへの参照をする段階で，同じ問題「teamかcharacterか」を引きずるような気もします(問題が増えたわけではないので，それはそれ)。書き方が複数あるので，Performerの定義において制約やレビューは難しくなると予想されます。memberは使わずにteamだけを使うようにする場合，PerformerはTeamと変わらなくなり，したがってPerformerを使ってチーム以外のものを表現する(i☆Risとか)ことはできなくなるか，そこでteamかreal_unitかのどちらか一方だけが入力可能，みたいな同種の問題をやはり持込みます。

----

たぶん，チームにチーム以外のものを持ち込もうとするときのミスマッチが気になるというのと，それが2パターン(以上)あって，別々の解決が必要ということかもしれません。

ひとつは，ライブがソロの場合で，チームにキャラクターをソロで持込む(Team - Characterの関係の話)ということですが，これは「チーム 真中らぁら」を受け入れるかどうかだけの問題にみえます。チーム一覧にも出てくることになるし，「真中らぁらはチーム真中らぁらのメンバーである」を受け入れる，というような。調べなおしてみて， https://schema.org/MusicGroup はソロも表わすというのがあり，倣うのも良いかもしれません。 (schema:performerはPerson or Organizationを指せるので，Character or Teamを指していても同様に良さそうではある)

もうひとつは，チームにi☆Risのようなリアルなアーティスト(CDのアーティスト欄)を持込む場合(Performer - Teamの関係の話)で，これはキャラクターから構成されないチームを考えないといけないかもしれなくて，するとチームとは別物である可能性も高いかなと思います。Teamを参照すべきLiveからはteamを，CDのアーティストを参照すべき(まだ見ぬ)主語からはPerformer(またはなんらかの相当する，あるいはPerformer or Teamな)主語を，参照するということになるかもしれなくて，別途そういうデータを集めてからやったほうがよいように見えます。

----

見えているメリットデメリット，他にも見えていないメリットデメリットありそうですが，一人チームを許容して(その影響で関連先のデータにも個人名チームが出てくることも許容して)，Performerは必要が例示されるまで持込まない，がバランス良いように思います。

下記やることリストの案:

* 「個人が歌う場合は一人のチームを作る」としてLiveのperformerはTeam
  * ただしなんらかの問題があれば `team/` `characters/` を頭に付ける運用にフォールバック，を考えておく
* 一人のチームは，キャラクターがあれば存在する，のではなく，必要に応じて参照されるときに手でteamsのCSVに作成する
  * CSVでデータだけ書けばRDFの生成を自動化する観点からは，それが`character/`にマッチするなら一人のチームをRDF上で生成してほしい・・・が，これは生成ロジックがPrismDB用になることを許容するかどうかで，どちらかというとPrismDBで使う場合には許容してよいと思う
* Performerが必要なケースがなんであるかは，例をつくって確認する

**Comment by takanakahiko** [comment]
> characterという語彙は追加されておらず

すみません、その通りでした。
カラムと語彙がごっちゃになっていました

**Comment by banjun** [comment]
e294ae6ab58d6e6f1c1d52f697b009378f4b1a1f 試しにソロチーム作ってみましたけどどうでしょう？ (チーム→メンバー参照はまだ)

ラベルが使い勝手のよいものがつくか、というのは考えてなくて、真中らぁらというラベルで、キャラのらぁらとチームのらぁらの両方が引けてしまうのはイマイチかもですね。

**Comment by takanakahiko** [comment]
ありがとうございます。
カラム名は team じゃなくて peformer でいい気がします

**Comment by banjun** [comment]
もうちょっと調べたり試行錯誤してたんですが，ソロチームやPerformerを作るのはデメリットが大きそうだなという感じになってきました。 **Performerについて考慮できる余地を残したうえで，「データとしてはLiveからTeamまたはCharacterを直接参照」が良いのではないか** と思います。以下イメージ(手書きがアレ)

![IMG_1978](https://user-images.githubusercontent.com/11156/71780084-899ba180-3001-11ea-9d1a-48958ddf243d.jpeg)

囲みのLive, Team, Character, Performerはそれぞれクラスを表わしています。その中にあるのが各々主語になるやつ(インスタンス，individual)です。

どうやらRDFではクラスには多重に適合することができます。というか，individualの集合のことをクラスと言っているからそうなるようです( https://www.w3.org/2001/sw/BestPractices/SE/ODSD/ )。他の例でみても `rdf:type` を複数持っているものはあるようです( http://ja.dbpedia.org/page/プリパラ )。あるインスタンスがコンテキストによって都度クラスに分類されているわけで，そのクラスのインスタンスが欲しいから同じインスタンスのクローン(ex. `character/らぁら` と `team/らぁら` とか `performer/らぁら` )を作るというものではないようにみえます。 ソロチームを作るとラベルがかぶってしまってうまく使えない問題は，この発想に逆行しているから起きているようです。

**結局のところ必要なのは，「LiveからTeam or Characterにあるインスタンスを参照を指定する書き方(CSVで)」** で，それは `team/` `character/` prefixでもよいし，カラム分けでも，csv2rdfがよしなにするでも，よいです。逆に，そこで分けないために統一された `performer/` prefixのインスタンスを導入する，または，`team/` で参照できるようにTeamのインスタンスをCharacterから複製して作る，というのが，ここでいう良くない例ということになると思います。

(上の図ではPerformerの囲みはPerformerクラスの存在を示唆していますが，実際にデータに盛り込むかは別途でもよさそうです。盛り込みたければ，対象のTeamかCharacterのインスタンスの `rdf:type` に `prism:Performer` を付けていくことで， `prism:performer` の対象は `prism:Performer` である，というような制約は検証できそうな(できそうな)雰囲気があります。Performer一覧も作れそうです。そのときのインスタンスは `team/` か `character/` を指します。が，これらはadditional taskな感じです。)

----

比較のために他パターンも参考として載せておきます。

![IMG_1979](https://user-images.githubusercontent.com/11156/71780312-54dd1980-3004-11ea-87b5-ab015f5c52ce.jpeg)

上のはソロチームを作る場合で， `team/らぁら` と `character/らぁら` が別物になります。が，コンテキストによっては別物ではないのです。別物でないと困るし別物であっても困る難しい状態です。

![IMG_1980](https://user-images.githubusercontent.com/11156/71780348-c9b05380-3004-11ea-9963-686c7036d08d.jpeg)

上のはPerformerを挟み，そこからTeamまたはCharacterに参照をはる方式です。やはりらぁらが複数ある問題は出てきます。ただしPerformerに属するものはPerformerであるということから，例えばラベルや名前を「`らぁら (パフォーマー)`」に改名してもらう，という方法は取りやすくはなるかもしれません。そのようなインスタンスが実在するのか・・・？はだいぶ曖昧という意味で微妙なポジションです。(比較して，1個上のソロチームの場合だと，SoLaMi♡SMILEは「`SoLaMi♡SMILE`」だが，らぁらは「`らぁら (チーム)`」というようなラベル振りができなくもないが，それはTeamに属するチームは(カッコ書き)なしで，Teamに属する非チームは(カッコ書き)ありで，というような解釈が必要になり苦しいです。そういう意味においてはPerformerのほうがソロチームに対するメリットはあるのだなと)

**Comment by takanakahiko** [comment]
図まで付けていただいてありがとうございます...！
そうですね，とりあえず Performer の導入は見送りにしましょうか．
「らぁら」が複数存在することに関する良くない点についてもよく理解できました．

勉強不足でいろいろ不便かけて申し訳ございません 🙏 

それを踏まえて，僕としては `team/` `character/` をつける案を推したいです．
このほうがCSVとRDFの構造が密になっていると思いました．

**Comment by banjun** [comment]
`team/` `character/` なら既存の仕組みだけでたぶん出来ますね。

もう一歩いくとcsv2rdfの機能として，CSVのセルを区切り文字で複数値として扱うのができたら(いまはできないですよね?)，performer(セパレーター=空白)が `...,character/らぁら character/みれぃ,...` とかできて，「二人で歌ったのでキャラクターソロではないが，チームとは呼べるのか？」みたいなパターンでも「二人で歌った」事実は表現できるのでよさそうです。たとえば「SoLaMi SMILE & DressingPafé & NonSugar & Tricolore & ガァルマゲドン & UCCHARI BIG-BANGS」は果たしてチームなのか？それらのチームがライブをしたのは事実であるが，すなわちそれらのユニオンのチームだったといえるのか？みたいな境界の例です。この機能自体は，「ケーキ、うなぎ」が好きなアイドルが「ケーキ」「うなぎ」が好き，と表現するのにも使えますし，別issueではありますね。現状はteam-member.csvで。

**Comment by takanakahiko** [comment]
そうですね．別Issueを建てておきます．ありがとうございます．
