### ISSUE TITLE
RDFにクラス情報が付与されない

### ISSUE THREAD

**Issue by takanakahiko** [prickathon/prismdb#27]
普通はRDFで定義する URI がどのクラスのインスタンスであるか定義するらしい
例えば `https://prismdb.takanakahiko.me/rdfs/characters/manaka_laala` のクラスは `https://prismdb.takanakahiko.me/preds/Character` です．みたいな．

考えている実装方法

- CSV2RDFで読み込む `xxxx-setting.json` でクラス名を指定する
- そこで，URIを生成する処理でクラス情報をRDFに書き込む

**Comment by banjun** [comment]
`rdf:type` ですかね 参考
https://github.com/imas/imasparql/blob/3fc5e9dc9118a4866df6814fdebbc1a1157c5961/RDFs/CinderellaGirls.rdf#L36

**Comment by banjun** [comment]
`pripara-characters.csv` だったら各行は `prismdb:Character`，みたいな知識というか対応づけを `xxxx-setting.json` に定義する感じでしょうか。
もしかするとさらに，CSVカラムと述語のマッピングもそこでもつのかな..とか。

**Comment by takanakahiko** [comment]
です！

ここで，たとえば，CSVで定義するようにすると

```
key,クラス,名前
manaka_laala,Character,真中らぁら
minami_mirei,Character,南みれぃ
```

みたいに，

- 「それ同CSVでは全部同じじゃん」なカラムが生えちゃう
- CSVではあまりRDFを意識しないようにしたいのに，意識せざるを得ない

みたいな弊害が出るので， CSV2RDF の処理内でどうにか出来ないかなといった感じです

**Comment by banjun** [comment]
CSVの各行にクラスを書くというのは厳しそう。Characterと非Characterと混ぜ書きする(混ぜ書きできうる)CSVのメンテナンスしやすさはなさそうなので。
CSVカラムと述語のマッピングは現状 `colmnsCsvPath` で実装済みですね。
