### ISSUE TITLE
GitHub Actionsのジョブの通知をSlackに送りたい

### ISSUE THREAD

**Issue by sue445** [prickathon/prismdb#308]
PRのビルドが通っていてもデプロイでコケていると気づかないため。

Slack通知系のActionはたくさんありますが、僕は https://github.com/marketplace/actions/slatify を使っててて特に不満点はないのでおすすめです。（ビルドの成功/失敗を簡潔に通知してくれる）

**Comment by takanakahiko** [comment]
いいですね。賛成です〜。
`#ci-prismdb` というチャンネルがあるので、それを使いたいっす
