### ISSUE TITLE
CSVのカラムがnamedNodeであるかliteralであるかを指定したい

### ISSUE THREAD

**Issue by takanakahiko** [prickathon/prismdb#34]
問題点

- 目的語(Object)がnamedNode(つまりはURI)である場合でも，現在のシステムでは問答無用でリテラル(つまりは文字列)で指定される
- 要するに目的語(Object)にURIを指定できない

考えていること

- `xxxx-columns.csv`(カラム定義CSV)にて，その目的語のタイプを指定する
- それに応じて `csv2rdf` でURIかリテラルか判断し，RDFへ変換する

考えるべきこと

- リテラルの場合は多言語対応を視野に入れる?( `xxxx-columns.csv` で指定?)
- プライマリデータCSVにURIを入力させることはそもそも「プライマリデータCSVを編集する人にRDFを意識させない」方針に反する?

**Comment by banjun** [comment]
リテラルの多言語対応は，RDFとSPARQLの仕様の組み合わせ上，付加的な機能「ではなく」，多言語対応しない場合とする場合とで使用方法が排他的に変わってしまうという問題があり，本当に必要な箇所だけ検討すればいいみたいな印象です。一旦は文字列リテラルは全てxsd:stringにしておくのが無難そう。

**Comment by takanakahiko** [comment]
それは知見ですね〜ありがとうございます．
では，多言語対応は一旦はしない方針で進めていきたいと思います．

**Comment by takanakahiko** [comment]
数字も考慮すべし

**Comment by banjun** [comment]
現状までで，なんとなく，できてるような？(整理はしてもよいが)

**Comment by takanakahiko** [comment]
そうですね，一度閉じます．
