### ISSUE TITLE
シリーズのRDF生成&エピソードCSVからのシリーズカラム削除したい

### ISSUE THREAD

**Issue by banjun** [prickathon/prismdb#43]
#39 でCSV側にシリーズカラムが足されていますが、CSVを編集しやすくするという観点からは無いほうがいいと思います。RDFに変換する仮定で必要な情報だから付加しているだけであり、CSVとしてはファイル名から明らかで、ただ一種類の値しか入れてはいけない(謎)カラムが増えてしまうので。

例えば、 `pripara-episodes.csv` は プリパラシリーズのエピソードを入れるためのCSVで、プリ☆チャンシリーズのCSVはそもそも分かれているため、そのなかでプリパラかプリ☆チャンかどちらのエピソードかを混ぜ書きできるという自由度が要らない、という意図です。(劇場版みたいな細かいのをどうするの?は別途議論あると思いますが)

シリーズ述語の値については、変換側の知識になると思います。現状から素直にいくと、columns定義の設定で、マスターCSVの値を参照するのではなく、直値で `"プリパラ"` を埋める設定を書ければ、 `pripara-episodes.csv` のシリーズ述語の値はどれもプリパラ、だけの話で済むようになります。

ただし、この先シリーズのRDFを生成するとなると、その生成がやるべきことは

* シリーズのリソースを定義する (たとえば `rdfs/series/pripara` とか)
* シリーズのエピソードとして、各エピソードへの参照を記載する
* 各エピソードのリソースからシリーズ述語でシリーズを参照する

となって、ここでシリーズ←→エピソード紐づけができそうなので、この生成を実装するときに、シリーズカラムをCSVから外すようにすれば、それで良さそうかな、と思います。

**Comment by takanakahiko** [comment]
ありがとうございます！

> 各エピソードのリソースからシリーズ述語でシリーズを参照する

ということを、CSV編集ユーザも認識しやすい方がいいかなと思い、シリーズカラムを追加した感じでした。（「ファイル名でわかる通り、裏で勝手に繋がっています」というルールを作りすぎると大変かなと思いました。）

ですから、seriesクラスの実装が終わったら、たとえばseriesカラムは`series/pripara` (series.csv ?への参照)とするつもりでした。

また、ばんじゅんさんの仰る通り、映画もまた考えなくちゃいけなくて、「映画毎にファイル作るのもなぁ。映画でseriesカラム使って、TVシリーズで使わないのもなぁ」みたいなことを思っていました。

ざっくりまとめると、多分ですが、僕としては「CSVを見たら参照が伸びているのがすぐにわかる」みたいな気持ちでやっていたところ、「編集する側としては不便だよね」といったご指摘だと思いました。

なんでCSVにするの？といった点から考える必要があるのかなと思いました。

ともあれ、まずはseriesクラス側の実装を先として、その後にこちらの問題に取り掛かる感じでいいですかね…？

**Comment by takanakahiko** [comment]
追加 : CSVのフォーマットがRESTの仕様に近い感じにしていると楽なのかなと思いました。「csvを見てみると、episodeのseriesはseriesインスタンスの参照になっているので、RESTでepisode取得したらseriesの参照を取得できるね」みたいな…？

**Comment by banjun** [comment]
結果はともあれそこに至る道筋は認識が違っていて，

> 「ファイル名でわかる通り、裏で勝手に繋がっています」というルール

は，勝手でもなんでもなく(と思っています)，ファイル名どおり，ここにはプリパラのエピソードを書くし，隣にはプリ☆チャンのエピソードを書くファイルがある，という以上のなにものでもないと思います。「シリーズカラムが無いから，プリ☆チャンのファイルがあるけれどもあえてプリパラのファイルにプリ☆チャンのエピソードを書いてもいいはずだ」とはならないと思ってます。

わたしはむしろ逆に，シリーズカラムによって，謎ルールが増えると思っているわけで，(=つまり，シリーズカラムによってルールが増えると思う派/減ると思う派，で認識が違う)，そこが認識ずれてると妥協点(？)も謎なものになりそうです。

> 各エピソードのリソースからシリーズ述語でシリーズを参照する

は，CSV編集ユーザは認識する必要がないのでは？と思っています。プリパラのファイルにプリパラのエピソードがある，ということを認識すれば十分です。シリーズとエピソードのリレーション(しかも参照と逆参照が要る)というのはRDF特有の知識であり，それを編集者に書かせる(コピペでいいよ！ではあるのだが)というのは，本当に必要なのか？ CSV編集ユーザにRDF知識を要求しすぎていないか？と心配になります。

> 僕としては「CSVを見たら参照が伸びているのがすぐにわかる」

これはまさにCSV→RDF変換実装者の気持ちとしてはよくわかるのですが，それをそのまま編集者に通しすぎては・・・？ということです

**Comment by banjun** [comment]
RESTとCSVの構造は近いほうがそれはいいんですけど，参照に関しては，たとえばキャラクターからチームへの参照はCSVには書かないはずですけど概念的には参照は存在するし，RESTでもSPARQLでもその参照はあって欲しいので，カラムとAPI構造は合わせられない(部分がある)ものとして扱うのがよいかと思います。

たぶんツリー構造に落とせる関係性は合わせられるけれども，それはマスターデータをある一つのツリー構造に落とすということで，他のツリー構造で見たいときには結局マスターデータの構造と違うところで参照定義になるし，ツリーじゃないただの双方向の関連構造でみたいということも(例えばキャラクターと曲の関係とか)あるんじゃないかと。
