### ISSUE TITLE
デプロイ時にトラフィック移行が行われない

### ISSUE THREAD

**Issue by sue445** [prickathon/prismdb#539]
https://github.com/prickathon/prismdb/pull/538 で「プリマジスタジオSoLaDo竹下通り店」が消えているはずなのに https://prismdb.takanakahiko.me/rdfs/shop/%E3%83%97%E3%83%AA%E3%83%9E%E3%82%B8%E3%82%B9%E3%82%BF%E3%82%B8%E3%82%AASoLaDo%E7%AB%B9%E4%B8%8B%E9%80%9A%E3%82%8A%E5%BA%97 には存在しているので、prismdbに最新のデータが反映されていないように見えます。

[2ヶ月前のデプロイ](https://github.com/prickathon/prismdb/actions/runs/5150874483/job/13944393495) だとDeploy to Cloud Runの最後に

```
Service [web] revision [web-00254-qun] has been deployed and is serving 100 percent of traffic.
```

が出ているのですが、 [最新のデプロイログ](https://github.com/prickathon/prismdb/actions/runs/5975860874/job/16212621854) には

```
Service [web] revision [web-00266-doy] has been deployed and is serving 0 percent of traffic.
```

と出ているので、デプロイした後の最新のリビジョンがアクティブになっておらず古いデータのままで動き続けてそうです

**Comment by takanakahiko** [comment]
あー、これは対応しなければ。
トラフィック以降が何かしらの原因で出来ていないので、デプロイ時のコマンドオプションとかから調べてみます。

**Comment by sue445** [comment]
今回の件と関係あるか分かりませんが、Dockerイメージのpush先に使っているContainer Registryが非推奨になっている [^1]ので対応した方がよさそうです

[^1]: https://cloud.google.com/container-registry/docs/deprecations/feature-deprecations?hl=ja

自分のGCPプロジェクトで動かしてるprismdbだと下記のようにArtifact Registryを使うようにしています

* https://github.com/sue445/prismdb/commit/2f43eb58aef0779f6349f0c61e32e2384df7e644
* https://github.com/sue445/prismdb/commit/1ad63baee7f9b4ba125b17a5a2c5c5399f5ef031

**Comment by takanakahiko** [comment]
とりあえず以下のコマンドを各 Version に実施してみました

```bash
gcloud run services update-traffic --to-latest
```

**Comment by takanakahiko** [comment]
> 今回の件と関係あるか分かりませんが、Dockerイメージのpush先に使っているContainer Registryが非推奨になっている [1](https://github.com/prickathon/prismdb/issues/539#user-content-fn-1-25f4e1cd5597a03fc76945a8ee7c33ff)ので対応した方がよさそうです

ありがとうございます！今回の問題と関連があるかわかりませんが、どちらにせよ対応したいところですね。

**Comment by takanakahiko** [comment]
適当に main ブランチで commit を push したところ、無事に

> Service [web] revision [web-00269-kpl] has been deployed and is serving 100 percent of traffic.

になりました 🎉 

https://github.com/prickathon/prismdb/actions/runs/6442083067/job/17492534240

**Comment by takanakahiko** [comment]
> 今回の件と関係あるか分かりませんが、Dockerイメージのpush先に使っているContainer Registryが非推奨になっている https://github.com/prickathon/prismdb/issues/539#user-content-fn-1-25f4e1cd5597a03fc76945a8ee7c33ffので対応した方がよさそうです

こちらは今回とは関係なかったですが、取り組みたいので別の Issue にしいておきますね！
