### ISSUE TITLE
/sparql がレスポンスを返さない

### ISSUE THREAD

**Issue by sue445** [prickathon/prismdb#556]
# 再現手順
https://prismdb.takanakahiko.me/ の[トップに載っているクエリを実行する](https://prismdb.takanakahiko.me/sparql?default-graph-uri=&query=PREFIX+prism%3A+%3Chttps%3A%2F%2Fprismdb.takanakahiko.me%2Fprism-schema.ttl%23%3E%0D%0A%0D%0ASELECT+%3Fn+%3Fst+%3Ftitle%0D%0AWHERE+%7B%0D%0A++++%3Flive+a+prism%3ALive%3B%0D%0A++++++++prism%3Aperformer%2Fprism%3Aname_kana+%22%E3%81%9D%E3%82%89%E3%81%BF%E3%81%99%E3%81%BE%E3%81%84%E3%82%8B%22%3B%0D%0A++++++++prism%3AsongPerformed%2Fprism%3Aname+%3Ftitle%3B%0D%0A++++++++prism%3AliveOfEpisode+%3Fep.%0D%0A++++%3Fep+a+prism%3AEpisode%3B%0D%0A++++++++prism%3A%E8%A9%B1%E6%95%B0+%3Fn%3B%0D%0A++++++++prism%3A%E3%82%B5%E3%83%96%E3%82%BF%E3%82%A4%E3%83%88%E3%83%AB+%3Fst.++%0D%0A%7D%0D%0AORDER+BY+%3Fn&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)

![image](https://github.com/prickathon/prismdb/assets/608755/8c434947-03ab-4ab8-ad97-2aac7caf963c)

# 期待する結果
1件以上の結果を返す

# 実際の挙動
空の結果が返る

![image](https://github.com/prickathon/prismdb/assets/608755/da28825e-f845-42fb-b116-9819994043d1)

# 原因
[少し前のmainブランチからforkした自分のprismdb](https://web-lk3h3ydj7a-an.a.run.app/sparql) だと問題ないので、おそらく #550 の中のどれかが原因だと思われます。（他に大きな変更が見当たらない...）

<img width="657" alt="image" src="https://github.com/prickathon/prismdb/assets/608755/df119031-5cd3-4d00-ae98-8b64154e1730">

**Comment by takanakahiko** [comment]
ありがとうございます！
時間あったら確認します

**Comment by takanakahiko** [comment]
多分直ると思う！ご迷惑おかけしました〜

**Comment by takanakahiko** [comment]
お、直ってる。

**Comment by sue445** [comment]
ヨシ！

<img width="710" alt="image" src="https://github.com/prickathon/prismdb/assets/608755/1502638d-b04b-4e63-9c7c-2b58d2701734">
